//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Verification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Verification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePerhilitanV2.App_LocalResources.Verification", typeof(Verification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        public static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEMALE.
        /// </summary>
        public static string _Betina {
            get {
                return ResourceManager.GetString("_Betina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE ACTION.
        /// </summary>
        public static string _DateAction {
            get {
                return ResourceManager.GetString("_DateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENT.
        /// </summary>
        public static string _Document {
            get {
                return ResourceManager.GetString("_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MALE.
        /// </summary>
        public static string _Jantan {
            get {
                return ResourceManager.GetString("_Jantan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAMPIRAN LESEN/PERMIT KHAS DIBATAL.
        /// </summary>
        public static string _LampiranLesenDibatal {
            get {
                return ResourceManager.GetString("_LampiranLesenDibatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAMPIRAN LESEN/PERMIT KHAS DIGANTUNG.
        /// </summary>
        public static string _LampiranLesenDigantung {
            get {
                return ResourceManager.GetString("_LampiranLesenDigantung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINISTRY APPROVAL.
        /// </summary>
        public static string _MinistryApproval {
            get {
                return ResourceManager.GetString("_MinistryApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTH.
        /// </summary>
        public static string _Month {
            get {
                return ResourceManager.GetString("_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO FILE ATTACHED.
        /// </summary>
        public static string _NoFileAttached {
            get {
                return ResourceManager.GetString("_NoFileAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT ACTIVE.
        /// </summary>
        public static string _NotActive {
            get {
                return ResourceManager.GetString("_NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LICENSE STATUS.
        /// </summary>
        public static string _StatusLesen {
            get {
                return ResourceManager.GetString("_StatusLesen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWNER STATUS.
        /// </summary>
        public static string _StatusPemilik {
            get {
                return ResourceManager.GetString("_StatusPemilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        public static string _TidakPasti {
            get {
                return ResourceManager.GetString("_TidakPasti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string _Ya {
            get {
                return ResourceManager.GetString("_Ya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Export Address.
        /// </summary>
        public static string E_AlamatEksport {
            get {
                return ResourceManager.GetString("E_AlamatEksport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Import Address!.
        /// </summary>
        public static string E_AlamatImport {
            get {
                return ResourceManager.GetString("E_AlamatImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Cites!.
        /// </summary>
        public static string E_CitesNo {
            get {
                return ResourceManager.GetString("E_CitesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert Copy Cites!.
        /// </summary>
        public static string E_CopyCites {
            get {
                return ResourceManager.GetString("E_CopyCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Location of Inspection!.
        /// </summary>
        public static string E_LokasiPemeriksaan {
            get {
                return ResourceManager.GetString("E_LokasiPemeriksaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Export Name!.
        /// </summary>
        public static string E_NamaEksport {
            get {
                return ResourceManager.GetString("E_NamaEksport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Import Name!.
        /// </summary>
        public static string E_NamaImport {
            get {
                return ResourceManager.GetString("E_NamaImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Inspection Officer!.
        /// </summary>
        public static string E_NamaPemeriksa {
            get {
                return ResourceManager.GetString("E_NamaPemeriksa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Verifier Officer Name!.
        /// </summary>
        public static string E_NamaPengesah {
            get {
                return ResourceManager.GetString("E_NamaPengesah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Export Country!.
        /// </summary>
        public static string E_NegaraEksport {
            get {
                return ResourceManager.GetString("E_NegaraEksport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Import Country!.
        /// </summary>
        public static string E_NegaraImport {
            get {
                return ResourceManager.GetString("E_NegaraImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Stem No!.
        /// </summary>
        public static string E_NoStem {
            get {
                return ResourceManager.GetString("E_NoStem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Quantity!.
        /// </summary>
        public static string E_QtySah {
            get {
                return ResourceManager.GetString("E_QtySah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Valid Date Permit!.
        /// </summary>
        public static string E_SahSehingga {
            get {
                return ResourceManager.GetString("E_SahSehingga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose License Status.
        /// </summary>
        public static string E_StatusLesen {
            get {
                return ResourceManager.GetString("E_StatusLesen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Owner Status.
        /// </summary>
        public static string E_StatusPemilik {
            get {
                return ResourceManager.GetString("E_StatusPemilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Status!.
        /// </summary>
        public static string E_StatusPengesah {
            get {
                return ResourceManager.GetString("E_StatusPengesah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Status!.
        /// </summary>
        public static string E_StatusPenyemak {
            get {
                return ResourceManager.GetString("E_StatusPenyemak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Details on No Permit.
        /// </summary>
        public static string E_Tab1 {
            get {
                return ResourceManager.GetString("E_Tab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Details on Wildlife List.
        /// </summary>
        public static string E_Tab2 {
            get {
                return ResourceManager.GetString("E_Tab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Details on Cites.
        /// </summary>
        public static string E_Tab3 {
            get {
                return ResourceManager.GetString("E_Tab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Details on Inspection.
        /// </summary>
        public static string E_Tab4 {
            get {
                return ResourceManager.GetString("E_Tab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Details on Semakan.
        /// </summary>
        public static string E_Tab5 {
            get {
                return ResourceManager.GetString("E_Tab5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Date and Time of Inspection.
        /// </summary>
        public static string E_TarikhMasaSemakan {
            get {
                return ResourceManager.GetString("E_TarikhMasaSemakan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Action Date.
        /// </summary>
        public static string E_TarikhTindakan {
            get {
                return ResourceManager.GetString("E_TarikhTindakan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Purpose!.
        /// </summary>
        public static string E_Tujuan {
            get {
                return ResourceManager.GetString("E_Tujuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert Comment!.
        /// </summary>
        public static string E_Ulasan {
            get {
                return ResourceManager.GetString("E_Ulasan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE ENTER ALL THIS INFORMATION : .
        /// </summary>
        public static string E_ValidationSummary {
            get {
                return ResourceManager.GetString("E_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON VALID.
        /// </summary>
        public static string NonValid {
            get {
                return ResourceManager.GetString("NonValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE CHOOSE.
        /// </summary>
        public static string PleaseChoose {
            get {
                return ResourceManager.GetString("PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string VV_AlertSaved {
            get {
                return ResourceManager.GetString("VV_AlertSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appendix.
        /// </summary>
        public static string VV_Appendix {
            get {
                return ResourceManager.GetString("VV_Appendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Name.
        /// </summary>
        public static string VV_ApplicantName {
            get {
                return ResourceManager.GetString("VV_ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked Application.
        /// </summary>
        public static string VV_ApplicationCheckedList {
            get {
                return ResourceManager.GetString("VV_ApplicationCheckedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string VV_Apply {
            get {
                return ResourceManager.GetString("VV_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appendix.
        /// </summary>
        public static string VV_Appndx {
            get {
                return ResourceManager.GetString("VV_Appndx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string VV_Approval {
            get {
                return ResourceManager.GetString("VV_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Quantity.
        /// </summary>
        public static string VV_ApprovedQuantity {
            get {
                return ResourceManager.GetString("VV_ApprovedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string VV_Category {
            get {
                return ResourceManager.GetString("VV_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        public static string VV_ChooseFile {
            get {
                return ResourceManager.GetString("VV_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITES.
        /// </summary>
        public static string VV_Cites_Info {
            get {
                return ResourceManager.GetString("VV_Cites_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITES NO.
        /// </summary>
        public static string VV_CITES_No {
            get {
                return ResourceManager.GetString("VV_CITES_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Cites Copy (if there changes).
        /// </summary>
        public static string VV_CitesChanges {
            get {
                return ResourceManager.GetString("VV_CitesChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perubahan Cites Dokumen.
        /// </summary>
        public static string VV_CitesUbah {
            get {
                return ResourceManager.GetString("VV_CitesUbah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string VV_Comment {
            get {
                return ResourceManager.GetString("VV_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Verifier.
        /// </summary>
        public static string VV_CommentVerifierOfficer {
            get {
                return ResourceManager.GetString("VV_CommentVerifierOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Name.
        /// </summary>
        public static string VV_CommonName {
            get {
                return ResourceManager.GetString("VV_CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Application.
        /// </summary>
        public static string VV_CompleteApplicationList {
            get {
                return ResourceManager.GetString("VV_CompleteApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Cites (Origin Country).
        /// </summary>
        public static string VV_Copy_Cites {
            get {
                return ResourceManager.GetString("VV_Copy_Cites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Company Registration.
        /// </summary>
        public static string VV_Copy_Register_Company {
            get {
                return ResourceManager.GetString("VV_Copy_Register_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Office Letter.
        /// </summary>
        public static string VV_CopyOfficeLetter {
            get {
                return ResourceManager.GetString("VV_CopyOfficeLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time Inspection.
        /// </summary>
        public static string VV_Date_Time_Inspection {
            get {
                return ResourceManager.GetString("VV_Date_Time_Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Date.
        /// </summary>
        public static string VV_DateApply {
            get {
                return ResourceManager.GetString("VV_DateApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        public static string VV_DateApproved {
            get {
                return ResourceManager.GetString("VV_DateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Date.
        /// </summary>
        public static string VV_DateCheck {
            get {
                return ResourceManager.GetString("VV_DateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Re-Check.
        /// </summary>
        public static string VV_DisemakSemula {
            get {
                return ResourceManager.GetString("VV_DisemakSemula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Information.
        /// </summary>
        public static string VV_Edit {
            get {
                return ResourceManager.GetString("VV_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string VV_EndDate {
            get {
                return ResourceManager.GetString("VV_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Entry Date.
        /// </summary>
        public static string VV_EntryDate {
            get {
                return ResourceManager.GetString("VV_EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of Exporter.
        /// </summary>
        public static string VV_ExportAddress {
            get {
                return ResourceManager.GetString("VV_ExportAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Country.
        /// </summary>
        public static string VV_ExportCountry {
            get {
                return ResourceManager.GetString("VV_ExportCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Exporter.
        /// </summary>
        public static string VV_ExportName {
            get {
                return ResourceManager.GetString("VV_ExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Export.
        /// </summary>
        public static string VV_ExportPurpose {
            get {
                return ResourceManager.GetString("VV_ExportPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string VV_Gender {
            get {
                return ResourceManager.GetString("VV_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License/Permit/Special Permit Holder.
        /// </summary>
        public static string VV_HolderLicense_Permit_SP {
            get {
                return ResourceManager.GetString("VV_HolderLicense/Permit/SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer Address.
        /// </summary>
        public static string VV_ImportAddress {
            get {
                return ResourceManager.GetString("VV_ImportAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Country.
        /// </summary>
        public static string VV_ImportCountry {
            get {
                return ResourceManager.GetString("VV_ImportCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer Name.
        /// </summary>
        public static string VV_ImporterName {
            get {
                return ResourceManager.GetString("VV_ImporterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Purpose.
        /// </summary>
        public static string VV_ImportPurpose {
            get {
                return ResourceManager.GetString("VV_ImportPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Address of Importer / Exporter.
        /// </summary>
        public static string VV_InfoAddressImporterExporter {
            get {
                return ResourceManager.GetString("VV_InfoAddressImporterExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Export Country Code. Eg : MY.
        /// </summary>
        public static string VV_InfoCodeExportCountry {
            get {
                return ResourceManager.GetString("VV_InfoCodeExportCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter the Comment.
        /// </summary>
        public static string VV_InfoComment {
            get {
                return ResourceManager.GetString("VV_InfoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose the Date and Time of Inspection.
        /// </summary>
        public static string VV_InfoDateTimeInspection {
            get {
                return ResourceManager.GetString("VV_InfoDateTimeInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed File in .pdf format only.
        /// </summary>
        public static string VV_InfoFailFormat {
            get {
                return ResourceManager.GetString("VV_InfoFailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Location of Inspection.
        /// </summary>
        public static string VV_InfoLocationInspection {
            get {
                return ResourceManager.GetString("VV_InfoLocationInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Name of Importer / Exporter.
        /// </summary>
        public static string VV_InfoNameImpoterExporter {
            get {
                return ResourceManager.GetString("VV_InfoNameImpoterExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name of Inspection Officer at Counter Check In.
        /// </summary>
        public static string VV_InfoNameInspectionOfficer {
            get {
                return ResourceManager.GetString("VV_InfoNameInspectionOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Valid Permit No.
        /// </summary>
        public static string VV_InfoPermitNo {
            get {
                return ResourceManager.GetString("VV_InfoPermitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Refer to the Code List : T - Commercial, Z - Zoo, G - Botanical Garden, Q - Circus or Travelling Exhibition, S - Sceintific, H - Hunting Trophy, P - Personal, M - Medical(including Biomedical Research), E - Educational, N - Reintroduction / Introduction into Wild, B - Breeding in Captivity / Artificial Propagation, L - Law Enforcement/Judicial,Forensic.
        /// </summary>
        public static string VV_InfoPurposeExport {
            get {
                return ResourceManager.GetString("VV_InfoPurposeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose the Status Application.
        /// </summary>
        public static string VV_InfoStatusApplication {
            get {
                return ResourceManager.GetString("VV_InfoStatusApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Stem No.
        /// </summary>
        public static string VV_InfoStemNo {
            get {
                return ResourceManager.GetString("VV_InfoStemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose the Type of License.
        /// </summary>
        public static string VV_InfoTypeLicense {
            get {
                return ResourceManager.GetString("VV_InfoTypeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose the Type of Matters.
        /// </summary>
        public static string VV_InfoTypeMatter {
            get {
                return ResourceManager.GetString("VV_InfoTypeMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Whether Cites or Non-Cites.
        /// </summary>
        public static string VV_InfoTypePermit {
            get {
                return ResourceManager.GetString("VV_InfoTypePermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Valid Date for Your Permit.
        /// </summary>
        public static string VV_InfoValidPermit {
            get {
                return ResourceManager.GetString("VV_InfoValidPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Until Date.
        /// </summary>
        public static string VV_InfoValidUntil {
            get {
                return ResourceManager.GetString("VV_InfoValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose the Verifier Officer.
        /// </summary>
        public static string VV_InfoVerifier {
            get {
                return ResourceManager.GetString("VV_InfoVerifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSPECTION.
        /// </summary>
        public static string VV_Inspection_Info {
            get {
                return ResourceManager.GetString("VV_Inspection_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of Inspection.
        /// </summary>
        public static string VV_Inspection_Location {
            get {
                return ResourceManager.GetString("VV_Inspection_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Officer Name.
        /// </summary>
        public static string VV_Inspection_Name {
            get {
                return ResourceManager.GetString("VV_Inspection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Application.
        /// </summary>
        public static string VV_InvalidApplicationList {
            get {
                return ResourceManager.GetString("VV_InvalidApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License / Permit.
        /// </summary>
        public static string VV_License_Permit {
            get {
                return ResourceManager.GetString("VV_License_Permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License/Permit/Special Permit Application.
        /// </summary>
        public static string VV_License_Permit_SpecialPermitApplication {
            get {
                return ResourceManager.GetString("VV_License/Permit/SpecialPermitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expired.
        /// </summary>
        public static string VV_LicenseExpired {
            get {
                return ResourceManager.GetString("VV_LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License No.
        /// </summary>
        public static string VV_LicenseNo {
            get {
                return ResourceManager.GetString("VV_LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Suspended/ Cancelled/ Probation.
        /// </summary>
        public static string VV_LicenseSuspended_Cancelled {
            get {
                return ResourceManager.GetString("VV_LicenseSuspended/Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type.
        /// </summary>
        public static string VV_LicenseType {
            get {
                return ResourceManager.GetString("VV_LicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Validated.
        /// </summary>
        public static string VV_LicenseValid {
            get {
                return ResourceManager.GetString("VV_LicenseValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string VV_List {
            get {
                return ResourceManager.GetString("VV_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WILDLIFE LIST.
        /// </summary>
        public static string VV_List_Wildlife {
            get {
                return ResourceManager.GetString("VV_List_Wildlife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Application.
        /// </summary>
        public static string VV_ListVerifiedApplication {
            get {
                return ResourceManager.GetString("VV_ListVerifiedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITES INFORMATION.
        /// </summary>
        public static string VV_MaklumatCites {
            get {
                return ResourceManager.GetString("VV_MaklumatCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string VV_No {
            get {
                return ResourceManager.GetString("VV_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string VV_No_Approved {
            get {
                return ResourceManager.GetString("VV_No_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string VV_No_Confirmed {
            get {
                return ResourceManager.GetString("VV_No_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR No.
        /// </summary>
        public static string VV_No_CR {
            get {
                return ResourceManager.GetString("VV_No_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON - CITES.
        /// </summary>
        public static string VV_NonCites {
            get {
                return ResourceManager.GetString("VV_NonCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking No.
        /// </summary>
        public static string VV_NoPenandaan {
            get {
                return ResourceManager.GetString("VV_NoPenandaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITES PERMIT NO.
        /// </summary>
        public static string VV_NoPermitCites {
            get {
                return ResourceManager.GetString("VV_NoPermitCites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string VV_Notes {
            get {
                return ResourceManager.GetString("VV_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Producer.
        /// </summary>
        public static string VV_OfficeProducer {
            get {
                return ResourceManager.GetString("VV_OfficeProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        public static string VV_Officer {
            get {
                return ResourceManager.GetString("VV_Officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original CITES No.
        /// </summary>
        public static string VV_Original_Cites_No {
            get {
                return ResourceManager.GetString("VV_Original_Cites_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder.
        /// </summary>
        public static string VV_Owner {
            get {
                return ResourceManager.GetString("VV_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder Name.
        /// </summary>
        public static string VV_OwnerName {
            get {
                return ResourceManager.GetString("VV_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application in Review Process.
        /// </summary>
        public static string VV_ProcessSemakSemula {
            get {
                return ResourceManager.GetString("VV_ProcessSemakSemula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string VV_Quantity {
            get {
                return ResourceManager.GetString("VV_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Checking.
        /// </summary>
        public static string VV_QuantityChecking {
            get {
                return ResourceManager.GetString("VV_QuantityChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Quantity.
        /// </summary>
        public static string VV_QuantityConfirmed {
            get {
                return ResourceManager.GetString("VV_QuantityConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string VV_Review {
            get {
                return ResourceManager.GetString("VV_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Info.
        /// </summary>
        public static string VV_Review_Info {
            get {
                return ResourceManager.GetString("VV_Review_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        public static string VV_Reviewer {
            get {
                return ResourceManager.GetString("VV_Reviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer Action.
        /// </summary>
        public static string VV_ReviewerAction {
            get {
                return ResourceManager.GetString("VV_ReviewerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer Officer.
        /// </summary>
        public static string VV_ReviewOfficer {
            get {
                return ResourceManager.GetString("VV_ReviewOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Checked Application .
        /// </summary>
        public static string VV_RevisedApplicationList {
            get {
                return ResourceManager.GetString("VV_RevisedApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size Cannot Exceed 2MB.
        /// </summary>
        public static string VV_SaizFile2MB {
            get {
                return ResourceManager.GetString("VV_SaizFile2MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Name.
        /// </summary>
        public static string VV_ScientificName {
            get {
                return ResourceManager.GetString("VV_ScientificName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string VV_Search {
            get {
                return ResourceManager.GetString("VV_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Information.
        /// </summary>
        public static string VV_SearchingInfo {
            get {
                return ResourceManager.GetString("VV_SearchingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Species Review.
        /// </summary>
        public static string VV_SearchSpeciesReview {
            get {
                return ResourceManager.GetString("VV_SearchSpeciesReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review &amp; Verification.
        /// </summary>
        public static string VV_SemakanPengesahan {
            get {
                return ResourceManager.GetString("VV_SemakanPengesahan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string VV_Source {
            get {
                return ResourceManager.GetString("VV_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string VV_Species {
            get {
                return ResourceManager.GetString("VV_Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string VV_StartDate {
            get {
                return ResourceManager.GetString("VV_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Status.
        /// </summary>
        public static string VV_Status_Application {
            get {
                return ResourceManager.GetString("VV_Status_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stem No.
        /// </summary>
        public static string VV_StemNo {
            get {
                return ResourceManager.GetString("VV_StemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string VV_Submit {
            get {
                return ResourceManager.GetString("VV_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Submission Date.
        /// </summary>
        public static string VV_SubmitSendFormDate {
            get {
                return ResourceManager.GetString("VV_SubmitSendFormDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through.
        /// </summary>
        public static string VV_Through {
            get {
                return ResourceManager.GetString("VV_Through", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Matters.
        /// </summary>
        public static string VV_Type_Matters {
            get {
                return ResourceManager.GetString("VV_Type_Matters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Search.
        /// </summary>
        public static string VV_TypeSearch {
            get {
                return ResourceManager.GetString("VV_TypeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Until.
        /// </summary>
        public static string VV_ValidUntil {
            get {
                return ResourceManager.GetString("VV_ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string VV_Verification {
            get {
                return ResourceManager.GetString("VV_Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Info.
        /// </summary>
        public static string VV_Verification_Info {
            get {
                return ResourceManager.GetString("VV_Verification_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifier.
        /// </summary>
        public static string VV_Verifier {
            get {
                return ResourceManager.GetString("VV_Verifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Officer.
        /// </summary>
        public static string VV_VerifyOfficer {
            get {
                return ResourceManager.GetString("VV_VerifyOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifier Officer Name.
        /// </summary>
        public static string VV_VerifyOfficerName {
            get {
                return ResourceManager.GetString("VV_VerifyOfficerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Action.
        /// </summary>
        public static string VV_ViewAction {
            get {
                return ResourceManager.GetString("VV_ViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string VV_ViewDetails {
            get {
                return ResourceManager.GetString("VV_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License Info.
        /// </summary>
        public static string VV_ViewLicenseInfo {
            get {
                return ResourceManager.GetString("VV_ViewLicenseInfo", resourceCulture);
            }
        }
    }
}
